In [1]:
!pip install ogb --quiet
!pip install torch_geometric --quiet
!pip install pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.4.0+cu121.html --quiet
!pip install  dgl -f https://data.dgl.ai/wheels/torch-2.4/cu121/repo.html --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.8/78.8 kB 2.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 kB 2.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 24.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 28.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 103.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.1/5.1 MB 3.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 83.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 986.2/986.2 kB 53.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 355.2/355.2 MB 4.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 797.2/797.2 MB 1.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 98.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

In [12]:
!git clone https://github.com/houyili/gipa_wide_deep.git

Cloning into 'gipa_wide_deep'...
remote: Enumerating objects: 71, done.
remote: Counting objects: 100% (71/71), done.
remote: Compressing objects: 100% (44/44), done.
remote: Total 71 (delta 36), reused 51 (delta 23), pack-reused 0 (from 0)
Receiving objects: 100% (71/71), 19.49 KiB | 9.74 MiB/s, done.
Resolving deltas: 100% (36/36), done.


In [3]:
import torch
torch.__version__

'2.4.0+cu121'

In [20]:
#/content/gipa_wide_deep/train_gipa.py

In [27]:
!source /content/gipa_wide_deep/run_deep_wide.sh

Streaming output truncated to the last 5000 lines.
Train/Val/Test: 0.5152/0.5139/0.5119
Best val/Final test score/Best Step: 0.5270/0.5260/70

Run: 1/10, Epoch: 101/1500, this epoch time: 2.49s Train loss/score: 0.3970/0.6548

Run: 1/10, Epoch: 102/1500, this epoch time: 2.48s Train loss/score: 0.3961/0.6571

Run: 1/10, Epoch: 103/1500, this epoch time: 2.48s Train loss/score: 0.3973/0.6594

Run: 1/10, Epoch: 104/1500, this epoch time: 2.68s Train loss/score: 0.3942/0.6606

Run: 1/10, Epoch: 105/1500, this epoch time: 2.53s Train loss/score: 0.3972/0.6525

Run: 1/10, Epoch: 105/1500, Average Train epoch time: 2.56s, Average Eval epoch time: 1.46s
Loss: 0.3972 Train/Val/Test loss: 0.7037/0.7167/0.6963
Train/Val/Test: 0.5154/0.5150/0.5135
Best val/Final test score/Best Step: 0.5270/0.5260/70

Run: 1/10, Epoch: 106/1500, this epoch time: 2.47s Train loss/score: 0.3936/0.6562

Run: 1/10, Epoch: 107/1500, this epoch time: 2.49s Train loss/score: 0.3938/0.6620

Run: 1/10, Epoch: 108/1500, th

In [ ]:
import torch
import dgl.function as fn
from ogb.nodeproppred import DglNodePropPredDataset, Evaluator
import numpy as np
import dgl
from copy import deepcopy

In [ ]:
data_dgl = DglNodePropPredDataset(name='ogbn-proteins', root='/content/gipa_wide_deep')

In [ ]:
splitted_idx = data_dgl.get_idx_split()
train_idx, val_idx, test_idx = splitted_idx["train"], splitted_idx["valid"], splitted_idx["test"]
graph, labels = data_dgl[0]
graph.ndata["labels"] = labels

In [ ]:
print(f"Nodes : {graph.number_of_nodes()}\n"
    f"Edges: {graph.number_of_edges()}\n"
    f"Train nodes: {len(train_idx)}\n"
    f"Val nodes: {len(val_idx)}\n"
    f"Test nodes: {len(test_idx)}")

Nodes : 132534
Edges: 79122504
Train nodes: 86619
Val nodes: 21236
Test nodes: 24679


In [ ]:
train_idx

tensor([    0,     1,     2,  ..., 86616, 86617, 86618])

In [ ]:
labels.shape

torch.Size([132534, 112])

In [ ]:
from pprint import pprint
pprint(graph)

Graph(num_nodes=132534, num_edges=79122504,
      ndata_schemes={'species': Scheme(shape=(1,), dtype=torch.int64), 'labels': Scheme(shape=(112,), dtype=torch.int64)}
      edata_schemes={'feat': Scheme(shape=(8,), dtype=torch.float32)})


In [ ]:

# Sample 10% of nodes
num_nodes = graph.number_of_nodes()
num_sampled_nodes = int(num_nodes * 0.1)
sampled_nodes = torch.randperm(num_nodes)[:num_sampled_nodes]

mapper = {
    node: index for index, node in enumerate(sampled_nodes.tolist())
}


# Create the sampled subgraph
sampled_graph = graph.subgraph(sampled_nodes)
sampled_labels = labels[sampled_nodes]

# Filter train, val, test indices for sampled nodes
def filter_indices(indices):
    return [mapper[idx.item()] for idx in indices if idx in sampled_nodes]

sampled_train_idx = filter_indices(train_idx)
sampled_val_idx = filter_indices(val_idx)
sampled_test_idx = filter_indices(test_idx)

# Print statistics for the sampled graph
print(f"Nodes : {sampled_graph.number_of_nodes()}\n"
      f"Edges: {sampled_graph.number_of_edges()}\n"
      f"Train nodes: {len(sampled_train_idx)}\n"
      f"Val nodes: {len(sampled_val_idx)}\n"
      f"Test nodes: {len(sampled_test_idx)}")

Nodes : 13253
Edges: 765024
Train nodes: 8605
Val nodes: 2130
Test nodes: 2518


In [ ]:
hetero_data = None
def change_pyg_hetero_data(path: str):
  data = torch.load(path)
  global hetero_data
  hetero_data = deepcopy(data)
  proteins, go_terms = data['protein', 'annotated', 'go_term']['edge_index']
  adj_matrix = torch.zeros((proteins.max().item()+1,go_terms.max().item()+1), dtype=torch.int64)

  # Iterate through the edge index and update the adjacency matrix
  for x, y in data['protein', 'annotated', 'go_term']['edge_index'].transpose(0, 1):
      adj_matrix[x, y] = 1

  del data['protein', 'annotated', 'go_term']
  del data['go_term']


  data['protein']['label'] = adj_matrix

  return data

### DATASET PPI


In [ ]:
# edge_index = data['protein', 'interacts', 'protein']['edge_index']
# edge_attr = data['protein', 'interacts', 'protein']['edge_attr']
# del data['protein', 'interacts', 'protein']
# data['edge_index'] = edge_index
# data['edge_attr'] = edge_attr

In [ ]:
dgl_graph = pyg_to_dgl(data)

In [ ]:
dgl_graph['feat']

DGLError: Invalid key "feat". Must be one of the edge types.

In [ ]:
from torch_geometric.utils import to_dgl

In [ ]:
data = change_pyg_hetero_data('graph_data.pt')
data = data.to_homogeneous()

<ipython-input-59-ffa89d9e3f37>:3: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  data = torch.load(path)


In [ ]:
true_y = data['label'][0, :]

In [ ]:
true_y.shape

torch.Size([5409])

In [ ]:
assert true_y.shape[-1] == 5409

In [ ]:
hetero_data['protein', 'interacts', 'protein']

{'edge_index': tensor([[ 7310,  7310,  7310,  ..., 16512, 16512, 16512],
        [ 4171,  1128,  6039,  ...,  6354,  3008,  2838]]), 'edge_attr': tensor([[  0,   0,   0,  ...,   0, 736, 767],
        [  0,   0,   0,  ..., 600, 141, 730],
        [  0,   0,   0,  ..., 600, 173, 745],
        ...,
        [  0,   0,   0,  ..., 900, 896, 999],
        [  0,   0,   0,  ...,   0, 131, 738],
        [  0,   0,   0,  ..., 600,  58, 963]])}

In [ ]:
data

Data(edge_index=[2, 505968], x=[16814, 1024], label=[16814, 5409], edge_attr=[505968, 8], node_type=[16814], edge_type=[505968])

In [ ]:
del data['node_type']
del data['edge_type']

In [ ]:
data['edge_attr']

tensor([[  0,   0,   0,  ...,   0, 736, 767],
        [  0,   0,   0,  ..., 600, 141, 730],
        [  0,   0,   0,  ..., 600, 173, 745],
        ...,
        [  0,   0,   0,  ..., 900, 896, 999],
        [  0,   0,   0,  ...,   0, 131, 738],
        [  0,   0,   0,  ..., 600,  58, 963]])

In [ ]:
converted_graph = to_dgl(data)

In [ ]:
converted_graph.edata

{'edge_attr': tensor([[  0,   0,   0,  ...,   0, 736, 767],
        [  0,   0,   0,  ..., 600, 141, 730],
        [  0,   0,   0,  ..., 600, 173, 745],
        ...,
        [  0,   0,   0,  ..., 900, 896, 999],
        [  0,   0,   0,  ...,   0, 131, 738],
        [  0,   0,   0,  ..., 600,  58, 963]]), 'feat': tensor([[  0,   0,   0,  ...,   0, 736, 767],
        [  0,   0,   0,  ..., 600, 141, 730],
        [  0,   0,   0,  ..., 600, 173, 745],
        ...,
        [  0,   0,   0,  ..., 900, 896, 999],
        [  0,   0,   0,  ...,   0, 131, 738],
        [  0,   0,   0,  ..., 600,  58, 963]])}

In [ ]:
converted_graph.num_nodes()

16814

In [ ]:
data

Data(edge_index=[2, 505968], label=[16814, 5409], edge_attr=[505968, 8], feat=[16814, 1024])

In [ ]:
converted_graph.edata['feat'] = converted_graph.edata['edge_attr']
del converted_graph.edata['edge_attr']

In [ ]:
converted_graph.edata['feat'] = converted_graph.edata['feat'].to(dtype=torch.float32)

In [ ]:
converted_graph.edata['feat'].dtype

torch.float32

In [ ]:
torch.tensor([0.7, 0.2, 0.51, 0.3]).round()

tensor([1., 0., 1., 0.])

In [ ]:
test_tensor = torch.tensor([[-1.1, 0.2], [0.51, 0.7]])

In [ ]:
test_tensor.sigmoid().round()

tensor([[0., 1.],
        [1., 1.]])